package com.dineshonjava.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios")
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id")
	private Integer id;
	@Column(name="username")
	private String username;
	@Column(name="password")
	private String password;
	@Column(name="nombres")
	private String nombres;
	@Column(name="apellidos")
	private String apellidos;
	@Column(name="correo")
	private String correo;
	@Column(name="bloqueado")
	private Byte bloqueado;
	@Column(name="ultimoIngreso")
	private Date ultimoIngreso;
	@Column(name="fechaRegistro")
	private Date fechaRegistro;
	@Column(name="fechaNacimiento")
	private Date fechaNacimiento;
	@Column(name="comprobado")
	private Byte comprobado;

	public Usuarios() {
	}

	public Usuarios(String username, String password, String nombres,
			String apellidos) {
		this.username = username;
		this.password = password;
		this.nombres = nombres;
		this.apellidos = apellidos;
	}

	public Usuarios(String username, String password, String nombres,
			String apellidos, String correo, Byte bloqueado,
			Date ultimoIngreso, Date fechaRegistro, Date fechaNacimiento,
			Byte comprobado) {
		this.username = username;
		this.password = password;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.correo = correo;
		this.bloqueado = bloqueado;
		this.ultimoIngreso = ultimoIngreso;
		this.fechaRegistro = fechaRegistro;
		this.fechaNacimiento = fechaNacimiento;
		this.comprobado = comprobado;
	
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

    public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	
	public Byte getBloqueado() {
		return this.bloqueado;
	}

	public void setBloqueado(Byte bloqueado) {
		this.bloqueado = bloqueado;
	}


	public Date getUltimoIngreso() {
		return this.ultimoIngreso;
	}

	public void setUltimoIngreso(Date ultimoIngreso) {
		this.ultimoIngreso = ultimoIngreso;
	}

	
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}


	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}


	public Byte getComprobado() {
		return this.comprobado;
	}

	public void setComprobado(Byte comprobado) {
		this.comprobado = comprobado;
	}

	

}
